[general]
import = [
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true
startup_mode = "Fullscreen"

[scrolling]
history = 100000
multiplier = 5

[font]
size = 14.0
offset = { x = 0, y = 4 }
normal = { family = "HackGen Console NF", style="Regular" }
bold = { family = "HackGen Console NF", style="Bold" }
italic = { family = "HackGen Console NF", style="Italic" }
bold_italic = { family = "HackGen Console NF", style="Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }
